---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: build
    image: "golang:1.13"
    commands:
      - go get github.com/schrej/godacov
      - ./run-tests.sh -ic ./...
      - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=drone.io; true
      - $GOPATH/bin/godacov -t $CODACY_TOKEN -r ./coverage.out -c $TRAVIS_COMMIT; true
    environment:
      COVERALLS_TOKEN:
        from_secret: coveralls_token
      CODACY_TOKEN:
        from_secret: codacy_token
